#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

PROGRAM=agent-e5573

echo "Copying $PROGRAM to $AGENT_E5573_HOST"
xz -9 --stdout "$PROGRAM" | ssh "$AGENT_E5573_HOST" "xz --decompress --verbose > $PROGRAM && chmod +x $PROGRAM"
