#!/bin/bash

set -euo pipefail
IFS=$'\n\t'
readonly SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

echo "Installing brew dependencies (may ask for your sudo password):"
brew bundle

echo Installing go dependencies:
go mod download
GOBIN="$SCRIPTS_DIR/../bin" go install github.com/onsi/ginkgo/ginkgo golang.org/x/lint/golint

echo Done.
